title: Jekyll + React
description: A jekyll just the docs app that has a react module inside of it.
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Jekyll React App on Github: https://github.com/JackGouldingay/jekyll-react-app
aux_links_new_tab: true

exclude:
  - spa-starter